### ISSUE TITLE
Please don't use the official TFC logo for your Github organisation.

### ISSUE THREAD

**Issue by dries007** [tfc-plus-addons/requests#2]
Please don't use the official TFC logo for your Github organisation.
Thanks!

**Comment by mabrowning** [comment]
Sorry, will change. I had expected to get notifications about this.... sorry for the delay!

**Comment by dries007** [comment]
Thanks very much. I just want to avoid as much confusion as possible.
If you would like to push builds of my addon ports to CurseForge, I can make you a project maintainer.
